version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
    container_name: petFinder
    volumes:
      - './postgres:/var/lib/postgresql/data'
